import type { Metadata } from "next";
import "./globals.css";
import TabMenu from "@/components/layout/TabMenu";
import { AuthProvider } from "@/components/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Hotel Managment System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <TabMenu />
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
